wes:
  serverProps:
    publicApiPort: 6000
    adminApiPort: 6001
  databaseProps:
    url: jdbc:sqlite:/db/wes.db
  serviceInfo:
    id: wes.starterkit.federatedgenomics.org
    name: Federated Genomics WES service
    description: Workflow Execution Service (WES) instance. Enables small-scale test workflows to be run over the web. Deployment of the GA4GH Starter Kit.
    contactUrl: mailto:info@elwazi.uct.ac.za
    documentationUrl: https://apidocs.federatedgenomics.org/wes
    createdAt: "2023-07-14T09:00:00Z"
    updatedAt: "2023-07-14T09:00:00Z"
    environment: development
    version: 1.0.0
    organization:
      name: CBIO
      url: https://cbio.uct.ac.za
  wesServiceProps:
    drsDockerContainer: true
